# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIs/window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FolderCreator(object):
    def setupUi(self, FolderCreator):
        FolderCreator.setObjectName("FolderCreator")
        FolderCreator.resize(420, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FolderCreator.sizePolicy().hasHeightForWidth())
        FolderCreator.setSizePolicy(sizePolicy)
        FolderCreator.setMinimumSize(QtCore.QSize(420, 400))
        self.centralwidget = QtWidgets.QWidget(FolderCreator)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.comboBox_type = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_type.setObjectName("comboBox_type")
        self.verticalLayout_3.addWidget(self.comboBox_type)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.lineEdit_nom = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nom.setObjectName("lineEdit_nom")
        self.verticalLayout_3.addWidget(self.lineEdit_nom)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.textEdit_description = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_description.setObjectName("textEdit_description")
        self.verticalLayout_3.addWidget(self.textEdit_description)
        self.groupBox_options = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_options.setObjectName("groupBox_options")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_options)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_excel = QtWidgets.QCheckBox(self.groupBox_options)
        self.checkBox_excel.setChecked(True)
        self.checkBox_excel.setObjectName("checkBox_excel")
        self.verticalLayout.addWidget(self.checkBox_excel)
        self.checkBox_autre = QtWidgets.QCheckBox(self.groupBox_options)
        self.checkBox_autre.setEnabled(False)
        self.checkBox_autre.setCheckable(True)
        self.checkBox_autre.setObjectName("checkBox_autre")
        self.verticalLayout.addWidget(self.checkBox_autre)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.groupBox_options)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_ann = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ann.setObjectName("pushButton_ann")
        self.horizontalLayout.addWidget(self.pushButton_ann)
        self.pushButton_creer = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_creer.setObjectName("pushButton_creer")
        self.horizontalLayout.addWidget(self.pushButton_creer)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        FolderCreator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FolderCreator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 420, 21))
        self.menubar.setObjectName("menubar")
        FolderCreator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FolderCreator)
        self.statusbar.setObjectName("statusbar")
        FolderCreator.setStatusBar(self.statusbar)

        self.retranslateUi(FolderCreator)
        QtCore.QMetaObject.connectSlotsByName(FolderCreator)

    def retranslateUi(self, FolderCreator):
        _translate = QtCore.QCoreApplication.translate
        FolderCreator.setWindowTitle(_translate("FolderCreator", "Créer un projet de simulation"))
        self.label.setText(_translate("FolderCreator", "Type :"))
        self.label_2.setText(_translate("FolderCreator", "Nom Projet :"))
        self.label_3.setText(_translate("FolderCreator", "Description Projet :"))
        self.groupBox_options.setTitle(_translate("FolderCreator", "Options"))
        self.checkBox_excel.setText(_translate("FolderCreator", "Créer feuilles Excel"))
        self.checkBox_autre.setText(_translate("FolderCreator", "Autres"))
        self.pushButton_ann.setText(_translate("FolderCreator", "Annuler"))
        self.pushButton_creer.setText(_translate("FolderCreator", "Créer"))
